CI: Compile on cosmopolitan C library (#132)

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -8,14 +8,6 @@ on:
 #    cancel-in-progress: false
 
 jobs:
-  clang-format:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    - name: Make check
-      run: |
-        make check
   build-and-test:
     # runs-on: self-hosted
     timeout-minutes: 5
@@ -29,6 +21,8 @@ jobs:
             - {os: ubuntu-latest, CXX: clang++, build_type: all}
             - {os: ubuntu-latest, CXX: clang++, build_type: release}
             - {os: ubuntu-latest, CXX: cmake, build_type: Debug}
+            - {os: ubuntu-latest, CXX: cosmoc++, build_type: all}
+            - {os: ubuntu-latest, CXX: cosmoc++, build_type: release}
             - {os: windows-latest, CXX: cl, build_type: Debug}
             - {os: windows-latest, CXX: g++, build_type: all}
             - {os: windows-latest, CXX: g++, build_type: release}
@@ -61,6 +55,25 @@ jobs:
       uses: ilammy/msvc-dev-cmd@v1.13.0
       with:
         arch: amd64
+    - name: Setup cosmoc++ 
+      if: matrix.config.CXX == 'cosmoc++'
+      shell: bash
+      run: |
+          if [[ "${{ matrix.config.os }}" == "windows-latest" ]]; then
+              choco install unzip wget -y --no-progress
+          fi
+          mkdir -p cosmocc
+          cd cosmocc
+          wget https://cosmo.zip/pub/cosmocc/cosmocc.zip -q
+          unzip -qq cosmocc.zip
+          git clone https://github.com/jart/cosmopolitan --depth=1
+          cd cosmopolitan
+          if [[ "${{ matrix.config.os }}" != "windows-latest" ]]; then
+              sudo ape/apeinstall.sh
+          fi
+          cd ..
+          cd ..
+          echo "$(pwd)/cosmocc/bin" >> $GITHUB_PATH
     - name: Output compiler version
       shell: bash
       run: |
@@ -73,14 +86,13 @@ jobs:
       if: matrix.config.CXX != 'cmake' && matrix.config.CXX != 'cl' && matrix.config.build_type == 'all'
       shell: bash
       run: |
-        # Enabling optimization checks -Wmaybe-uninitialized from -Wall
         # output 3 to stdin (to close the game) as 'make all' will start the game
-        echo -e "3" | CXXFLAGS=-O2 CXX=${{ matrix.config.CXX }} make all -j2
+        echo -e "3" | make CXX=${{ matrix.config.CXX }} all -j2
     - name: Make release
       if: matrix.config.CXX != 'cmake' && matrix.config.CXX != 'cl' && matrix.config.build_type == 'release'
       shell: bash
       run: |
-        CXX=${{ matrix.config.CXX }} make release -j 2
+        make release CXX=${{ matrix.config.CXX }} -j 2
     - name: CMake
       if: matrix.config.CXX == 'cmake'
       shell: bash
@@ -105,6 +117,7 @@ jobs:
         else
             executable="stocksim"
         fi
+        echo -e "1\ntest\nX\nY\n" | ./$executable
         echo -e "0\n saves\nsaves\nB\n1\n1\nN\nY\nN\nY\nN\nY\nT\n0\nT\n1\nT\n2\nE\nT\nX\nY\n" | ./$executable
         # test for loading saves
         echo -e "1\nsaves\nN\nY\nN\nY\nN\nY\nN\nY\nT\n0\nT\nT\n3\nT\n4\nT\nS\n1\n1\nX\nY\n" | ./$executable
@@ -120,3 +133,79 @@ jobs:
         path: stocksim*
         compression-level: 9
         if-no-files-found: error
+  analyze:
+    needs: build-and-test
+    name: CodeQL Analysis (${{ matrix.language }})
+    # Runner size impacts CodeQL analysis time. To learn more, please see:
+    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
+    #   - https://gh.io/supported-runners-and-hardware-resources
+    #   - https://gh.io/using-larger-runners (GitHub.com only)
+    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
+    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
+    permissions:
+        # required for all workflows
+        security-events: write
+        # required to fetch internal or private CodeQL packs
+        packages: read
+        # only required for workflows in private repositories
+        actions: read
+        contents: read
+    strategy:
+        fail-fast: false
+        matrix:
+            include:
+            - language: c-cpp
+              build-mode: autobuild
+            # CodeQL supports the following values keywords for 'language': 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
+            # Use `c-cpp` to analyze code written in C, C++ or both
+            # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
+            # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
+            # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis,
+            # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
+            # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
+            # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
+    steps:
+        - name: Checkout repository
+          uses: actions/checkout@v4
+        # Initializes the CodeQL tools for scanning.
+        - name: Initialize CodeQL
+          uses: github/codeql-action/init@v3
+          with:
+            languages: ${{ matrix.language }}
+            build-mode: ${{ matrix.build-mode }}
+            # If you wish to specify custom queries, you can do so here or in a config file.
+            # By default, queries listed here will override any specified in a config file.
+            # Prefix the list here with "+" to use these queries and those in the config file.
+
+            # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+            queries: security-extended,security-and-quality
+
+        # If the analyze step fails for one of the languages you are analyzing with
+        # "We were unable to automatically build your code", modify the matrix above
+        # to set the build mode to "manual" for that language. Then modify this step
+        # to build your code.
+        # ℹ️ Command-line programs to run using the OS shell.
+        # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+        - if: matrix.build-mode == 'manual'
+          shell: bash
+          run: |
+            echo 'If you are using a "manual" build mode for one or more of the' \
+                'languages you are analyzing, replace this with the commands to build' \
+                'your code, for example:'
+            echo '  make bootstrap'
+            echo '  make release'
+            exit 1
+        - name: Perform CodeQL Analysis
+          uses: github/codeql-action/analyze@v3
+          with:
+            category: "/language:${{matrix.language}}"
+  clang-format:
+    runs-on: ubuntu-latest
+    needs: build-and-test
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Make check
+        run: |
+          make check
